name: Deploy with SSH and Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Deploy via SSH with Password
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            script: |
                # Define variables
                WORK_DIR="/root/"
                
                
                # Pull the repository
                cd $WORK_DIR
                if [ -d "react-fe" ]; then
                  rm -rf "react-fe"
                fi
                git clone https://github.com/ScissorhandsMetu/react-fe.git
                
                if docker service ls | grep -q "${{ github.event.repository.name }}"; then
                    docker service rm ${{ github.event.repository.name }}
                fi
                # Build the Docker image
                cd "${{ github.event.repository.name }}"
                docker build -t "${{ github.event.repository.name }}:${{ github.run_id }}" .
                
                # Remove the local repository copy
                cd ..
                rm -rf "${{ github.event.repository.name }}"
                
                # Deploy or Update the Service
                if docker service ls | grep -q "${{ github.event.repository.name }}"; then
                  # Update the service if it already exists
                  docker service update --with-registry-auth --image "${{ github.event.repository.name }}:${{ github.run_id }}" "${{ github.event.repository.name }}"
                else
                  # Create the service if it doesn't exist
                  docker service create  --with-registry-auth --name "${{ github.event.repository.name }}" --publish 3000:3000 "${{ github.event.repository.name }}:${{ github.run_id }}"
                fi